### ISSUE TITLE
Rethinking what the colors for current amount of currency mean for seasonal currencies

### ISSUE THREAD

**Issue by Protuhj** [Canettieri/currenciesmulti#31]
What the colors mean for how much currency you currently have might need to be re-thought when it comes to seasonal currencies.

![image](https://github.com/Canettieri/currenciesmulti/assets/1165219/f30baa6a-c9e2-4ad7-823c-df9f2bcac41f)

~~You can see that once you've earned a lot for the season, the current amount will always be orange/red...~~

~~Maybe the color for the current amount maybe be tied how much you can still earn? That might make more sense.~~

Any thoughts?

The existing code just needs to be adjusted a little bit...

**Comment by Protuhj** [comment]
Should the weekly increase amount be somehow tied to the color of your current amount? Because seasonal currencies will be mostly red for the majority of an expansion if there's not some other condition taken into account.

For the image above, the seasonal max is currently 540, so once you earn over 426.6, the text will be red.. I'm not sure what formula makes the most sense.

**Comment by Canettieri** [comment]
Text being red is an alert to the users to use this currency or soon they will cannot acquire more. There is no reason for the user to track and don't use it.

**Comment by Protuhj** [comment]
For seasonal currencies, like the crests, "use it or lose it" doesn't really apply, since there's only so much you can earn at all each week. 

For example: once you've earned 400, you can't spend down and then earn back up.

Maybe the color for the weekly-increasing currencies should be based on how much you have left to earn, with respect to the weekly increase amount, instead of caring how much you currently have.


Say you're capped when a new week starts, then you have the full 90 to earn still, so the amount is white.
Then we apply the color logic to the "can earn" amount, with respect to the 90 increase, instead of the total earned amount that we currently apply it to.

I'll put together a pull request to show what I mean.
