### ISSUE TITLE
Lua error after Titan Panel Update 

### ISSUE THREAD

**Issue by Odysseas68** [Canettieri/currenciesmulti#37]
After today's update of Titan Panel i got on login the following error:

1x TitanCurrenciesMulti/Core/Menus.lua:4: bad argument #1 to 'insert' (table expected, got string)
[string "=[C]"]: in function `insert'
[string "@TitanCurrenciesMulti/Core/Menus.lua"]:4: in main chunk

Locals:
(*temporary) = "TITAN_PANEL_MENU_CATEGORIES"
(*temporary) = "Currency [Dragonflight]"
(*temporary) = "table expected, got string"

**Comment by Odysseas68** [comment]
Also i got 1 more error (Titan Panel ver 8.0.7 retail) :

1x AceLocale-3.0-6: Titan: Missing entry for 'TITAN_PANEL_MENU_CATEGORIES'
[string "@TitanCurrenciesMulti/Core/Menus.lua"]:2: in main chunk

Locals:
ADDON_NAME = "TitanCurrenciesMulti"
L = <table> {
 SLCurrency18Title = "Tower Knowledge"
 showAltText = "Show Alts"
 NoSightless = "Acquired in Dalaran Sewers."
 NoNether = "Acquired in Broken Shore and at the Legion invasions in Broken Isles."
 Elib = <function> defined @TitanCurrenciesMulti/Core/Elib-4.0.lua:108
 AzeritetoLvL = "Azerite to Up:|cFFFFFFFF "
 NoSLCurrency14 = "Obtainable through Mythic+."
 addDigitSeparator = "Add thousands separator for large numbers"
 seasonEarn = "Total season earns:"
 maxBar = "Show Maximum Value on bar"
 totalbank = "Total in Bank: "
 mShadowlands = "[|cFF198ae0Shadowlands|r]"
 HallowEnd = "Available through the event
Hallow's End."
 NoLegionfall = "Can be acquired in Broken
Shore."
 NoCurious = "Found in random drops in Broken Isles."
 SLCurrency18Description = "Manifestation of knowledge
gained in Torghast. Used to
unlock the power within
The Box of Many Things."
 NoTimeless = "Available through Timeless Isle."
 NoBrokenFate = "Can be exchanged with
Archmage Lan'dalock in
Dalaran."
 AzeritetoMaximum = "This Level Maximum Power:|cFFFFFFFF "
 info = "|cFFFFFFFF[Information]|r"
 mLegion = "[|cFF198ae0Legion|r]"
 GoldPlayerTip = "|cFFB4EEB4Hint:|r |cFFFFFFFFLeft-click opens ${player}|cFFFFFFFF's currency window.|r"
 NoSLCurrency13 = "Obtainable through Command Table."
 Utils = <table> {
 }
 NoDrowned = "Fish in the Margoss' Retreat, close to Dalaran."
 AltChars = "|cFFFFFFFF[All Characters]|r"
 AzeriteXP = "Current Power:|cFFFFFFFF "
 DraenorOnly = "Available in Draenor."
 PrepareCurrenciesMenu = <function> defined @TitanCurrenciesMulti/Core/CurrenciesCore.lua:90
 PrepareCurrenciesMenuBase = <function> defined @TitanCurrenciesMulti/Core/CurrenciesCore.lua:45
 NoSLCurrency17 = "Obtainable through Sanctum of
Domination bosses."
 hideInfoWhenHyperlink = "Hide extra info when showing hyperlink"
 dragonf = "Currency [Dragonflight]"
 NoTB = "Available through daily
quests in Tol Barad."
 SLShared02 = "Acquired in Torghast."
 misc = "Currency [Misc]"
 mPvE = "[|cFF198ae0PvE|r]"
 noheart = "|cFFFF2e2eNo Heart of Azeroth!"
 TradersTender = "Obtained from your capital's Trading Post."
 royalJ = "|cffa335eeRoyal Jelly|r"
 VisionsOnly = "Available in Visions of N'Zoth content."
 bfa = "Currency [BfA]"
 SLShared01 = "Acquired in Zereth Mortis."
 NoIronpaw = "Available through cooking quests in Pandaria."
 showbb = "Display Session Balance in Bar"
 NoMana = "Acquired in Suramar."
 wotlk = "Currency [WotLK]"
 useHyperlink = "Show tooltip as hyperlink"
 showAllFactions = "Characters from Both Factions"
 tooltip = "Tooltip"
 buttonText = "Bar Text"
 TotalAlt = "Currency Total:"
 AzeriteLevel = "Heart of Azeroth Level:|cFFFFFFFF "
 simpleText = "Show Simple Text"
 DragonFOnly = "Available in Dragon Isles."
 canGet = "Can still get: "
 mWoD = "[|cFF198ae0WoD|r]"
 totalAcquired = "Total acquired: "
 NoMaxOil = "Available through Shipyard in
Warlords of Draenor."
 NoLove = "Available through the event
Love is in the Air."
 GoldTitle = "Gold"
 mBfA = "[|cFF198ae0BfA|r]"
 mOther = "[|cFF198ae0Others|r]"
 NoPpearl = "Available in Nazjatar."
 legacy = "Currency [Legacy]"
 maxpermitted = "Maximum permitted: "
 mPvP = "[|cFF198ae0PvP|r]"
 NoToken = "Available through the event
Brewfest."
 NoCAir = "Rogue only, available in Legion."
 mMoP = "[|cFF198ae0MoP|r]"
 NoBrawler = "Available through Brawler's Guild
fights."
 mEvent = "[|cFF198ae0Event|r]"
 mCata = "[|cFF198ae0Cata|r]"
 NoEpicurean = "Available through cooking
quests in old Dalaran
(Northrend) and capital cities."
 sortByAmount = "Sort by amount"
 PandariaOnly = "Available in Pandaria."
 NoLKCurrency04 = "Rewarded from level 80
Jewelcrafting daily quests in
Dalaran."
 AzeriteDescription = "Artifact Power empowers the Heart of Azeroth."
 SLOnly = "Available in Shadowlands."
 LegionOnly = "Available in Broken Isles."
 NoAncestry = "Available through the event
Lunar Festival."
 session = "Session balance: "
 BfAOnly = "Available in Battle for Azeroth."
 NoWorldTree = "Available through daily
quests in Mount

**Comment by Canettieri** [comment]
Unfortunately the version 8.0.6 of Titan Panel removed the function I useds to categorize the currencies in the addon (_TITAN_PANEL_MENU_CATEGORIES_). I have quick fixed it for now, but I'm talking about it with the Titan Panel creator, HonorGoG.

Thank you for your report.

**Comment by Canettieri** [comment]
Please, friend. Update Titan to v8.0.8 and my addon to the lastest version too.

Thank you for your feedback! 😁
