### ISSUE TITLE
4 modules have error

### ISSUE THREAD

**Issue by Odysseas68** [Canettieri/currenciesmulti#47]
After today update of addon to version 10.1.0 4 modules still have the same error:

1x ...nCurrenciesMulti/c.Legacy/BfA/TitanArtifactPower.lua:10: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@TitanCurrenciesMulti/c.Legacy/BfA/TitanArtifactPower.lua"]:10: in main chunk

Locals:
ADDON_NAME = "TitanCurrenciesMulti"

----------------------------

1x ...Ons/TitanCurrenciesMulti/c.Legacy/BfA/TitanJelly.lua:10: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@TitanCurrenciesMulti/c.Legacy/BfA/TitanJelly.lua"]:10: in main chunk

Locals:
ADDON_NAME = "TitanCurrenciesMulti"

-----------------------

1x ...aceTitanCurrenciesMulti/c.Misc/TitanGold.lua:9: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@TitanCurrenciesMulti/c.Misc/TitanGold.lua"]:9: in main chunk

Locals:
ADDON_NAME = "TitanCurrenciesMulti"

------------------------------

1x ...urrenciesMulti/c.Shadowlands/TitanTowerKnowledge.lua:9: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@TitanCurrenciesMulti/c.Shadowlands/TitanTowerKnowledge.lua"]:9: in main chunk

Locals:
ADDON_NAME = "TitanCurrenciesMulti"

I didn't paste all the lua text. not to spam the message.

**Comment by Canettieri** [comment]
Thank you, friend.
Fixed in v10.1.1
