### ISSUE TITLE
Update Tower Knowledge currency to show seasonal max/etc similar to Valor

### ISSUE THREAD

**Issue by lostmimic** [Canettieri/currenciesmulti#5]
Update the currency to show the seasonal maxes and how much you can still gain.

PR for the change

https://github.com/Canettieri/currenciesmulti/pull/4

**Comment by Canettieri** [comment]
Hello, friend. I've changed the code by my own and the version is now live. Your pull request has an error in the localization, 2 lines. I've explained in your PR.

Thank you again for all and sorry by the delay in solving this case. :)

**Comment by lostmimic** [comment]
Thanks for fixing the two issues (I was on vacation and just got back!) 

Glad you cut a new release :)
