### ISSUE TITLE
Wrong/Missing Jewelcrafting Currency in Cataclysm Classic category

### ISSUE THREAD

**Issue by SilAntoine** [Canettieri/currenciesmulti#54]
Hello,

Under Cataclysm category, WOTLK jewelcrafting's currency is listed instead otof Cataclysm's one.

Cheers mate!

<img width="567" alt="{CED7BF50-3274-422B-ACCD-974E8D712D76}" src="https://github.com/user-attachments/assets/c4a3fac9-4f2b-40fb-b53e-828c8dc71ea5">

<img width="342" alt="{2452A071-F448-4087-9BCC-40688A6FBCFA}" src="https://github.com/user-attachments/assets/4f5126d9-04d4-49f5-a5cd-2366349d975e">

**Comment by Canettieri** [comment]
Oh, I'm sorry... I fixed this bug in v10.5.0.
Thanks for your report!

**Comment by SilAntoine** [comment]
Works like a charm, thanks a bunch!

**Comment by Canettieri** [comment]
You are welcome, friend!
