### ISSUE TITLE
[Request] Cataclysm Classic - New Firelands currency

### ISSUE THREAD

**Issue by SilAntoine** [Canettieri/currenciesmulti#56]
Hello,

Could you add "Mark of the World Tree" which has been implemented with Firelands prepatch?

<img width="342" alt="{58AAB0DF-52C7-4D8F-ABBF-BE104873CAA0}" src="https://github.com/user-attachments/assets/2565d931-73db-4e7e-898d-eab98e67335d">

Many thanks,
Antoine

**Comment by Canettieri** [comment]
Done, friend. Enjoy v10.6.0!

**Comment by SilAntoine** [comment]
You're the man! Thank you!
