### ISSUE TITLE
[Request] Cataclysm Classic - Fissure Stone Fragments

### ISSUE THREAD

**Issue by SilAntoine** [Canettieri/currenciesmulti#59]
Hello!

Would it be possible to add "Fissure Stone Fragment" currencies to Cataclysm Classic?

Item ID is 3148 if I'm not mistaken.

Many thanks!

<img width="341" alt="{311C2E9A-BDBE-4EF0-89E2-C1A7805BD2DC}" src="https://github.com/user-attachments/assets/bf8de06b-5c40-4a8b-9a91-63debaa5c8aa">

**Comment by Canettieri** [comment]
Done in v10.8.0.
Enjoy it, friend.
