### ISSUE TITLE
Don't show a random cap when the currency is uncapped

### ISSUE THREAD

**Issue by romdeau23** [Canettieri/currenciesmulti#7]
Hello.

Currently, valor is not capped, but the addon shows an incorrect "can still get" value. It's even negative in the tooltip.

It would be nice to hide this when a currency is no longer capped and just display it the same way as other currencies.

![image](https://user-images.githubusercontent.com/43295566/172453102-859ee2c7-05d5-4e2c-93b8-fd98729af7b6.png)

**Comment by Canettieri** [comment]
It has been solved in v9.0.1.

Thank you! :)
